version: '3'
services:  
  dashboard:
    image: dashboard:v1.60
    volumes:
      - ./logs/dashboard:/app/logs
    ports:
      - 8502:8501
    restart: always

  redis:
    image: redis
    restart: always
    command: redis-server --save 20 1
    volumes:
      - ./cache:/data
    ports:
          - '127.0.0.1:6379:6379'